<?php

/**
 * @file
 * Core settings file; @see https://api.drupal.org/api/drupal/sites%21default%21default.settings.php/7.x.
 */
$conf['theme_debug'] = TRUE;
$update_free_access = TRUE;
$drupal_hash_salt = 'o1dRyplQPhEVAlURk7pS5wA231jrrFKVQS4VbBmTT1w';

ini_set('session.gc_probability', 1);
ini_set('session.gc_divisor', 100);
ini_set('session.gc_maxlifetime', 200000);
ini_set('session.cookie_lifetime', 2000000);

$conf['404_fast_paths_exclude'] = '/\/(?:styles)\//';
$conf['404_fast_paths'] = '/\.(?:txt|png|gif|jpe?g|css|js|ico|swf|flv|cgi|bat|pl|dll|exe|asp)$/i';
$conf['404_fast_html'] = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>';
//$conf['https'] = TRUE; // bug sessions duplicate

if (file_exists('/var/www/site-php')) {
  require '/var/www/site-php/inseadedu/inseadedu-settings.inc';
}

if (isset($conf['memcache_servers'])) {
  $conf['cache_backends'][] = './sites/all/modules/contrib/memcache/memcache.inc';
  $conf['cache_default_class'] = 'MemCacheDrupal';
  $conf['cache_class_cache_form'] = 'DrupalDatabaseCache';
  $conf['cache_class_cache_page'] = 'DrupalFakeCache';
}

include 'env.settings.php';
error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
// <DDSETTINGS>
// Please don't edit anything between <DDSETTINGS> tags.
// This section is autogenerated by Acquia Dev Desktop.
if (isset($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR']) && file_exists($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/loc_insead_acquia_dev_dd.inc')) {
  require $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/loc_insead_acquia_dev_dd.inc';
}
// </DDSETTINGS>
